# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.52501794 0.44189202 0.77449873]
  [0.46074976 0.86062472 0.43907676]
  [0.18347049 0.25735215 0.84795461]]

 [[0.12463895 0.52525827 0.31809869]
  [0.39311322 0.4495558  0.02070087]
  [0.25661984 0.64169212 0.45780239]]

 [[0.39582606 0.05786116 0.28335691]
  [0.54354914 0.89586728 0.52245032]
  [0.49803673 0.94610583 0.02971982]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [17]:
import numpy as np
a = np.diag(1+np.arange(5))
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [28]:
import numpy as np
a = np.ones((3,3))
print(a)
a = np.zeros((8,8))
print(a)
a[1::2,::2] = 1
print(a)
a[::2,1::2] = 1
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [44]:
import numpy as np
a = np.random.random((5,5))
print("Original Array :")
print(a)
amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)
print("After normalization :")
print(a)

Original Array :
[[0.98307183 0.34364446 0.71221677 0.04781705 0.27226333]
 [0.81962467 0.11067962 0.55092163 0.1077257  0.76524357]
 [0.70855672 0.8493302  0.92005429 0.53795617 0.81013782]
 [0.2631061  0.01405576 0.92552788 0.63652368 0.70420319]
 [0.29316153 0.35934404 0.6372964  0.09512807 0.26096941]]
After normalization :
[[1.         0.34012717 0.72048445 0.0348408  0.26646366]
 [0.83132668 0.09971337 0.55403196 0.096665   0.77520676]
 [0.71670737 0.86198204 0.9349675  0.54065193 0.82153649]
 [0.25701363 0.         0.94061611 0.6423711  0.71221464]
 [0.28803008 0.35632875 0.64316853 0.08366456 0.25480862]]


# 5.  How to find common values between two arrays?

In [45]:
import numpy as np
array1 = np.array([1, 2, 3 , 4, 5, 6])
print("Array1 is : ",array1)
array2 = [5,6,7,8,9]
print("Array2 is : ",array2)
print("Common values between two arrays are :")
print(np.intersect1d(array1, array2))

Array1 is :  [1 2 3 4 5 6]
Array2 is :  [5, 6, 7, 8, 9]
Common values between two arrays are :
[5 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [47]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's date is : ",yesterday)
today     = np.datetime64('today', 'D')
print("Today's date is : ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is : ",tomorrow)

Yestraday's date is :  2020-07-27
Today's date is :  2020-07-28
Tomorrow's date is :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [52]:
a = np.random.randint(0,2)
print("First array is :")
print(a)
b = np.random.randint(0,2)
print("Second array is :")
print(b)
print("Test above two arrays are equal or not mention below :-")
array_equal = np.allclose(a,b)
print(array_equal)

First array is :
0
Second array is :
1
Test above two arrays are equal or not mention below :-
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [54]:
a = np.random.random(10)
print("Original array is :")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0 : ")
print(a)

Original array is :
[0.30585768 0.30480551 0.927722   0.1454953  0.91517484 0.10234848
 0.49299177 0.36804477 0.5619744  0.40488922]
Maximum value replaced by 0 : 
[0.30585768 0.30480551 0.         0.1454953  0.91517484 0.10234848
 0.49299177 0.36804477 0.5619744  0.40488922]


# 9. How to print all the values of an array?

In [62]:
array1 = np.arange(10)
print("All values of an array are as follows ")
print(array1)

All values of an array are as follows 
[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [68]:
print(" Original matrix: ")
X = np.random.rand(2,4)
print(X)
print("\n Subtract the mean of each row of the said matrix: ")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

 Original matrix: 
[[0.78827801 0.81746413 0.90317432 0.36727755]
 [0.38432615 0.94516048 0.13908631 0.81153512]]

 Subtract the mean of each row of the said matrix: 
[[ 0.06922951  0.09841563  0.18412582 -0.35177095]
 [-0.18570087  0.37513346 -0.4309407   0.2415081 ]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [79]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[5. 2. 2. 6. 2. 4. 3. 1. 3. 2.]


# 12.How to get the diagonal of a dot product?

# 13.How to find the most frequent value in an array?

In [87]:
a = np.random.randint(0,4,4)
print("Original array:")
print(a)
print("Most frequent value in the above array:")
print(np.bincount(a).argmax())

Original array:
[0 2 2 2]
Most frequent value in the above array:
2


# 14.How to get the n largest values of an array

In [95]:
a = np.arange(10)
print("Original array is :")
print(a)
np.random.shuffle(a)
n = 1
print (a[np.argsort(a)[-n:]])

Original array is :
[0 1 2 3 4 5 6 7 8 9]
[9]


# 15.How to create a record array from a regular array?

In [96]:
array1 = np.array([("Teddy", 88.5, 90), ("Adi", 87.5, 99), ("Ritti", 85.5, 91)])
print("Original arrays:")
print(array1)
print("\nRecord array;")
result = np.core.records.fromarrays(array1.T, names='col1, col2, col3', formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Teddy' '88.5' '90']
 ['Adi' '87.5' '99']
 ['Ritti' '85.5' '91']]

Record array;
[(b'Teddy', 88.5, 90) (b'Adi', 87.5, 99) (b'Ritti', 85.5, 91)]
